; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:dueUSB]
platform = atmelsam
board = dueUSB
framework = arduino
board_build.variants_dir = ${PROJECT_DIR}/variants
build_flags =
    -DSAM3X8
    -include ${PROJECT_INCLUDE_DIR}/sam3x8_ext.h
    -I${PROJECT_INCLUDE_DIR}
    -Wl,--allow-multiple-definition
board_build.usb_product = MIPS, native USB
board_vendor = GAA Custom Electronics, LLC
extra_scripts =
    pre:print_variant.py
    post:help_file_creator.py